using System;
using System.Collections.Generic;
using System.Text;

namespace S2p.RestClient.Sdk.Entities
{
    public class Helper
    {
        private static readonly Dictionary<string, string> Countries = new Dictionary<string, string>()
        {
            {"AD", "Andorra"},
            {"AE", "United Arab Emirates"},
            {"AF", "Afghanistan"},
            {"AG", "Antigua and Barbuda"},
            {"AI", "Anguilla"},
            {"AL", "Albania"},
            {"AM", "Armenia"},
            {"AN", "Netherlands Antilles"},
            {"AO", "Angola"},
            {"AQ", "Antarctica"},
            {"AR", "Argentina"},
            {"AS", "American Samoa"},
            {"AT", "Austria"},
            {"AU", "Australia"},
            {"AW", "Aruba"},
            {"AX", "Aland Islands"},
            {"AZ", "Azerbaijan"},
            {"BA", "Bosnia & Herzegowina"},
            {"BB", "Barbados"},
            {"BD", "Bangladesh"},
            {"BE", "Belgium"},
            {"BF", "Burkina Faso"},
            {"BG", "Bulgaria"},
            {"BH", "Bahrain"},
            {"BI", "Burundi"},
            {"BJ", "Benin"},
            {"BM", "Bermuda"},
            {"BN", "Brunei Darussalam"},
            {"BO", "Bolivia"},
            {"BR", "Brazil"},
            {"BS", "Bahamas"},
            {"BT", "Bhutan"},
            {"BV", "Bouvet Island"},
            {"BW", "Botswana"},
            {"BY", "Belarus"},
            {"BZ", "Belize"},
            {"CA", "Canada"},
            {"CC", "Cocos (Keeling) Islands"},
            {"CD", "Congo, Democratic Republic of the"},
            {"CF", "Central African Republic"},
            {"CG", "Congo"},
            {"CH", "Switzerland"},
            {"CI", "Ivory Coast"},
            {"CK", "Cook Islands"},
            {"CL", "Chile"},
            {"CM", "Cameroon"},
            {"CN", "China"},
            {"CO", "Colombia"},
            {"CR", "Costa Rica"},
            {"CU", "Cuba"},
            {"CV", "Cape Verde"},
            {"CX", "Christmas Island"},
            {"CY", "Cyprus"},
            {"CZ", "Czech Republic"},
            {"DE", "Germany"},
            {"DJ", "Djibouti"},
            {"DK", "Denmark"},
            {"DM", "Dominica"},
            {"DO", "Dominican Republic"},
            {"DZ", "Algeria"},
            {"EC", "Ecuador"},
            {"EE", "Estonia"},
            {"EG", "Egypt"},
            {"EH", "Western Sahara"},
            {"ER", "Eritrea"},
            {"ES", "Spain"},
            {"ET", "Ethiopia"},
            {"FI", "Finland"},
            {"FJ", "Fiji Islands"},
            {"FK", "Falkland Islands"},
            {"FM", "Micronesia, Federated States of"},
            {"FO", "Faroe Islands"},
            {"FR", "France"},
            {"FX", "France, Metropolitan"},
            {"GA", "Gabon"},
            {"GB", "United Kingdom"},
            {"GD", "Grenada"},
            {"GE", "Georgia"},
            {"GF", "French Guiana"},
            {"GG", "Guernsey"},
            {"GH", "Ghana"},
            {"GI", "Gibraltar"},
            {"GL", "Greenland"},
            {"GM", "Gambia"},
            {"GN", "Guinea"},
            {"GP", "Guadeloupe"},
            {"GQ", "Equatorial Guinea"},
            {"GR", "Greece"},
            {"GS", "South Georgia and the South Sandwich Islands"},
            {"GT", "Guatemala"},
            {"GU", "Guam"},
            {"GW", "Guinea-Bissau"},
            {"GY", "Guyana"},
            {"HK", "Hong Kong"},
            {"HM", "Heard and McDonald Islands"},
            {"HN", "Honduras"},
            {"HR", "Croatia"},
            {"HT", "Haiti"},
            {"HU", "Hungary"},
            {"ID", "Indonesia"},
            {"IE", "Ireland"},
            {"IL", "Israel"},
            {"IM", "Isle of Man"},
            {"IN", "India"},
            {"IO", "British Indian Ocean Territory"},
            {"IQ", "Iraq"},
            {"IR", "Iran, Islamic Republic of"},
            {"IS", "Iceland"},
            {"IT", "Italy"},
            {"JM", "Jamaica"},
            {"JO", "Jordan"},
            {"JP", "Japan"},
            {"KE", "Kenya"},
            {"KG", "Kyrgyzstan"},
            {"KH", "Cambodia (formerly Kampuchea)"},
            {"KI", "Kiribati"},
            {"KM", "Comoros"},
            {"KN", "Saint Kitts (Christopher) and Nevis"},
            {"KP", "Korea, Democratic People\"s Republic of (North Korea)"},
            {"KR", "Korea, Republic of (South Korea)"},
            {"KW", "Kuwait"},
            {"KY", "Cayman Islands"},
            {"KZ", "Kazakhstan"},
            {"LA", "Lao People\"s Democratic Republic"},
            {"LB", "Lebanon"},
            {"LC", "Saint Lucia"},
            {"LI", "Liechtenstein"},
            {"LK", "Sri Lanka"},
            {"LR", "Liberia"},
            {"LS", "Lesotho"},
            {"LT", "Lithuania"},
            {"LU", "Luxembourg"},
            {"LV", "Latvia"},
            {"LY", "Libyan Arab Jamahiriya"},
            {"MA", "Morocco"},
            {"MC", "Monaco"},
            {"MD", "Moldova, Republic of"},
            {"ME", "Montenegro"},
            {"MG", "Madagascar"},
            {"MH", "Marshall Islands"},
            {"MK", "Macedonia, the Former Yugoslav Republic of"},
            {"ML", "Mali"},
            {"MM", "Myanmar"},
            {"MN", "Mongolia"},
            {"MO", "Macao"},
            {"MP", "Northern Mariana Islands"},
            {"MQ", "Martinique"},
            {"MR", "Mauritania"},
            {"MS", "Montserrat"},
            {"MT", "Malta"},
            {"MU", "Mauritius"},
            {"MV", "Maldives"},
            {"MW", "Malawi"},
            {"MX", "Mexico"},
            {"MY", "Malaysia"},
            {"MZ", "Mozambique"},
            {"NA", "Namibia"},
            {"NC", "New Caledonia"},
            {"NE", "Niger"},
            {"NF", "Norfolk Island"},
            {"NG", "Nigeria"},
            {"NI", "Nicaragua"},
            {"NL", "Netherlands"},
            {"NO", "Norway"},
            {"NP", "Nepal"},
            {"NR", "Nauru"},
            {"NU", "Niue"},
            {"NZ", "New Zealand"},
            {"OM", "Oman"},
            {"PA", "Panama"},
            {"PE", "Peru"},
            {"PF", "French Polynesia"},
            {"PG", "Papua New Guinea"},
            {"PH", "Philippines"},
            {"PK", "Pakistan"},
            {"PL", "Poland"},
            {"PM", "St Pierre and Miquelon"},
            {"PN", "Pitcairn Island"},
            {"PR", "Puerto Rico"},
            {"PS", "Palestine, State of"},
            {"PT", "Portugal"},
            {"PW", "Palau"},
            {"PY", "Paraguay"},
            {"QA", "Qatar"},
            {"RE", "Réunion"},
            {"RO", "Romania"},
            {"RU", "Russian Federation"},
            {"RS", "Serbia"},
            {"RW", "Rwanda"},
            {"SA", "Saudi Arabia"},
            {"SB", "Solomon Islands"},
            {"SC", "Seychelles"},
            {"SD", "Sudan"},
            {"SE", "Sweden"},
            {"SG", "Singapore"},
            {"SH", "St Helena"},
            {"SI", "Slovenia"},
            {"SJ", "Svalbard and Jan Mayen Islands"},
            {"SK", "Slovakia"},
            {"SL", "Sierra Leone"},
            {"SM", "San Marino"},
            {"SN", "Senegal"},
            {"SO", "Somalia"},
            {"SR", "Suriname"},
            {"ST", "Sco Tomé and Prkncipe"},
            {"SU", "Union of Soviet Socialist Republics"},
            {"SV", "El Salvador"},
            {"SY", "Syrian Arab Republic"},
            {"SZ", "Swaziland"},
            {"TC", "Turks and Caicos Islands"},
            {"TD", "Chad"},
            {"TF", "French Southern and Antarctic Territories"},
            {"TG", "Togo"},
            {"TH", "Thailand"},
            {"TJ", "Tajikistan"},
            {"TK", "Tokelau"},
            {"TM", "Turkmenistan"},
            {"TN", "Tunisia"},
            {"TO", "Tonga"},
            {"TP", "East Timor"},
            {"TR", "Turkey"},
            {"TT", "Trinidad and Tobago"},
            {"TV", "Tuvalu"},
            {"TW", "Taiwan, Province of China"},
            {"TZ", "Tanzania, United Republic of"},
            {"UA", "Ukraine"},
            {"UG", "Uganda"},
            {"UM", "United States Minor Outlying Islands"},
            {"US", "United States of America"},
            {"UY", "Uruguay"},
            {"UZ", "Uzbekistan"},
            {"VA", "Holy See"},
            {"VC", "Saint Vincent and the Grenadines"},
            {"VE", "Venezuela"},
            {"VG", "Virgin Islands (British)"},
            {"VI", "Virgin Islands (US)"},
            {"VN", "Viet Nam"},
            {"VU", "Vanautu"},
            {"WF", "Wallis and Futuna Islands"},
            {"WS", "Samoa"},
            {"XO", "West Africa"},
            {"YE", "Yemen"},
            {"YT", "Mayotte"},
            {"ZA", "South Africa"},
            {"ZM", "Zambia"},
            {"ZW", "Zimbabwe"},
            {"AA", "International"}

        };

        private static readonly Dictionary<string, string> Currencies = new Dictionary<string, string>()
        {
            { "AED", "UAE Dirham"},
            { "AFN", "Afghanistan Afghanis"},
            { "ALL", "Lek"},
            { "AMD", "Dram (Russian Ruble [RUR] was formerly in use)"},
            { "ANG", "Netherlands Antilles Guilder (Florin)"},
            {"AOA", "Angola Kwanza"},
            {"AON", "New Kwanza (replacement for Kwanza)"},
            {"ARA", "Austral Neuvo Peso"},
            {"ARS", "Argenintinian Neuvo Peso"},
            {"AUD", "Australian Dollar"},
            {"AWG", "Aruban Guilder (Florin)"},
            {"AZM", "Azerbaijani Manat"},
            {"AZN", "Azerbaijan New Manats"},
            {"BAM", "Convertible Mark"},
            {"BBD", "Barbados Dollar"},
            {"BDT", "Taka"},
            {"BGN", "Bulgaria Leva"},
            {"BHD", "Bahraini Dinar"},
            {"BIF", "Burundi Franc"},
            {"BMD", "Bermudian Dollar"},
            {"BND", "Brunei Dollar"},
            {"BOB", "Boliviano Peso"},
            {"BOP", "Bolivian Peso"},
            {"BRL", "Brazilian real"},
            {"BRR", "Cruzeiro Real"},
            {"BSD", "Bahamian Dollar"},
            {"BTN", "Ngultrum (Indian Rupee also circulates)"},
            {"BWP", "Pula"},
            {"BYR", "Belarussian Rouble"},
            {"BZD", "Belize Dollar"},
            {"CAD", "Canadian Dollar"},
            {"CDF", "Congo/Kinshasa Francs"},
            {"CDZ", "New Zalre"},
            {"CHF", "Swiss Franc"},
            {"CLF", "Unidades de Fomento Peso"},
            {"CLP", "Chilean Peso"},
            {"CNY", "Yuan Renminbi"},
            {"COP", "Colombian Peso"},
            {"CRC", "Costa Rican Colón"},
            {"CSD", "Serbian Dinar"},
            {"CUC", "Cuba Convertible Pesos"},
            {"CUP", "Cuban Peso"},
            {"CVE", "Escudo Caboverdiano"},
            {"CYP", "Cypriot Pound"},
            {"CZK", "Czech Koruna"},
            {"DJF", "Djibouti Franc"},
            {"DKK", "Danish Krone"},
            {"DOP", "Dominican Republic Peso"},
            {"DZD", "Algerian Dinar"},
            {"EEK", "Kroon"},
            {"EGP", "Egytian Pound"},
            {"ERN", "Eritreian Nakfa, Ethiopian Birr"},
            {"ETB", "Eritreian Nakfa, Ethiopian Birr"},
            {"EUR", "Euro"},
            {"FJD", "Fiji Dollar"},
            {"FKP", "Falkland Pound"},
            {"GBP", "Pound Sterling"},
            {"GEL", "Lari"},
            {"GGP", "Guernsey Pounds"},
            {"GHC", "Cedi"},
            {"GHS", "Ghana Cedis"},
            {"GIP", "Gibraltar Pound"},
            {"GMD", "Dalasi"},
            {"GNF", "Guinea Francs"},
            {"GNS", "Guinea Syli (also known as Guinea Franc)"},
            {"GQE", "Franc de la Communauté financicre africaine and Ekwele"},
            {"GTQ", "Quetzal"},
            {"GWP", "Guinea-Bissau Peso and Franc de la Communauté financicre africaine"},
            {"GYD", "Guyana Dollar"},
            {"HKD", "Hong Kong Dollar"},
            {"HNL", "Lempira"},
            {"HRD", "Kuna and Croatian Dinar"},
            {"HRK", "Kuna and Croatian Dinar"},
            {"HTG", "Gourde"},
            {"HUF", "Forint"},
            {"IDR", "Rupiah"},
            {"ILS", "Shekel"},
            {"IMP", "Isle of Man Pounds"},
            {"INR", "Ngultrum or Indian Rupee"},
            {"IQD", "Iraqi Dinar"},
            {"IRR", "Iranian Rial"},
            {"ISK", "Icelandic Króna"},
            {"JEP", "Jersey Pounds"},
            {"JMD", "Jamaican Dollar"},
            {"JOD", "Jordanian Dinar"},
            {"JPY", "Yen"},
            {"KES", "Kenyan Shilling"},
            {"KGS", "Kyrgyzstani Som"},
            {"KHR", "Riel"},
            {"KMF", "Comorian Franc"},
            {"KPW", "North Korean Won"},
            {"KRW", "South Korean Won"},
            {"KWD", "Kuwaiti Dinar"},
            {"KYD", "Cayman Islands Dollar"},
            {"KZT", "Tenge (Russian Ruble [RUR] was formerly in use)"},
            {"LAK", "Kip"},
            {"LBP", "Lebanese Pound"},
            {"LKR", "Sri Lankan Rupee"},
            {"LRD", "Liberian Dollar"},
            {"LSL", "Loti and South African Rand"},
            {"LSM", "Maloti and South African Rand"},
            {"LTL", "Litas"},
            {"LVL", "Lats"},
            {"LYD", "Libyan Dinar"},
            {"MAD", "Moroccan Dirham and Mauritanian Ouguiya"},
            {"MDL", "Moldovian Leu"},
            {"MGA", "Madagascar Ariary"},
            {"MGF", "Malagasy Franc"},
            {"MKD", "Macedonian Dinar"},
            {"MMK", "Kyat"},
            {"MNT", "Tugrik"},
            {"MOP", "Pataca"},
            {"MRO", "Moroccan Dirham and Mauritanian Ouguiya"},
            {"MTL", "Maltese Lira (Maltese Pound formerly in use)"},
            {"MUR", "Mauritius Rupee"},
            {"MVR", "Rufiyaa"},
            {"MWK", "Malawian Kwacha"},
            {"MXN", "Mexican New Peso (replacement for Mexican Peso)"},
            {"MYR", "Ringgit (Malaysian Dollar)"},
            {"MZM", "Metical"},
            {"MZN", "Mozambique Meticais"},
            {"NAD", "Namibian Dollar and South African Rand"},
            {"NGN", "Naira"},
            {"NIC", "Córdoba"},
            {"NIO", "Nicaragua Cordobas"},
            {"NOK", "Norwegian Krone"},
            {"NPR", "Nepalese Rupee"},
            {"NZD", "New Zealand Dollar"},
            {"OMR", "Rial Omani"},
            {"PAB", "Balboa and US Dollar"},
            {"PEI", "Inti and New Sol (New Sol replaced Sol)"},
            {"PEN", "Inti and New Sol (New Sol replaced Sol)"},
            {"PGK", "Kina"},
            {"PHP", "Philippines Peso"},
            {"PKR", "Pakistani Rupee"},
            {"PLN", "New Zloty (replacement for Zloty)"},
            {"PYG", "Guarani"},
            {"QAR", "Qatari Riyal"},
            {"RON", "Romanian Leu"},
            {"RSD", "Serbia Dinars"},
            {"RUB", "Russian Federation Rouble"},
            {"RWF", "Rwanda Franc"},
            {"SAR", "Saudi Riyal"},
            {"SBD", "Solomon Islands Dollar"},
            {"SCR", "Pound Sterling (United Kingdom Pound), Seychelles Rupee"},
            {"SDD", "Sudanese Pound and Sudanese Dinar"},
            {"SDG", "Sudan Pounds"},
            {"SDP", "Sudanese Pound and Sudanese Dinar"},
            {"SEK", "Swedish Krona"},
            {"SGD", "Singapore Dollar"},
            {"SHP", "St Helena Pound"},
            {"SIT", "Tolar"},
            {"SKK", "Slovak Koruna"},
            {"SLL", "Leone"},
            {"SOS", "Somali Shilling"},
            {"SPL", "Seborga Luigini"},
            {"SRD", "Suriname Dollars"},
            {"SRG", "Surinam Guilder (also known as Florin)"},
            {"STD", "Dobra"},
            {"SUR", "USSR Rouble"},
            {"SVC", "El Salvadorian Colón"},
            {"SYP", "Syrian Pound"},
            {"SZL", "Lilangeni"},
            {"THB", "Baht"},
            {"TJR", "Tajik Rouble (Russian Ruble [RUR] was formerly in use)"},
            {"TJS", "Tajikistan Somoni"},
            {"TMM", "Turkmenistani Manat"},
            {"TMT", "Turkmenistan New Manats"},
            {"TND", "Tunisian Dinar"},
            {"TOP", "Pa'anga"},
            {"TPE", "Timorian Escudo"},
            {"TRL", "Turkish Lira"},
            {"TRY", "Turkey New Lira"},
            {"TTD", "Trinidad and Tobago Dollar"},
            {"TVD", "Tuvalu Dollars"},
            {"TWD", "New Taiwan Dollar"},
            {"TZS", "Tanzanian Shilling"},
            {"UAH", "Hryvna and Karbovanet"},
            {"UAK", "Hryvna and Karbovanet"},
            {"UGS", "Ugandan Shilling"},
            {"UGX", "Uganda Shillings"},
            {"USD", "US Dollar"},
            {"UYU", "Uruguayan New Peso (replacement for Uruguayan Peso)"},
            {"UZS", "Uzbekistani Som (Russian Ruble [RUR] was formerly in use)"},
            {"VEB", "Bolivar"},
            {"VEF", "Venezuela Bolivares Fuertes"},
            {"VND", "Dong"},
            {"VUV", "Vatu"},
            {"WST", "Tala"},
            {"XAF", "Guinea-Bissau Peso and Franc de la Communauté financicre africaine"},
            {"XAG", "Silver Ounces"},
            {"XAU", "Gold Ounces"},
            {"XCD", "East Caribbean Dollar"},
            {"XDR", "International Monetary Fund Special Drawing Rights"},
            {"XOF", "West African Franc and Franc de la Communauté financicre africaine"},
            {"XPD", "Palladium Ounces"},
            {"XPF", "Franc des Comptoirs franeais du Pacifique"},
            {"XPT", "Platinum Ounces"},
            {"YER", "Riyal (Dinar was used in South Yemen)"},
            {"ZAR", "Loti, Namibian Dollar, Maloti and South African Rand"},
            {"ZMK", "Zambian Kwacha"},
            {"ZMW", "Zambia Kwacha"},
            {"ZWD", "Zimbabwe Dollar"}
        };

        public static Dictionary<string, string> GetCountries()
        {
            return Countries;
        }

        public static Dictionary<string, string> GetCurrencies()
        {
            return Currencies;
        }

        public static bool CountryExists(string countryCode)
        {
            return Countries.ContainsKey(countryCode) ? true : false;
        }

        public static bool CurrencyExists(string currencyCode)
        {
            return Currencies.ContainsKey(currencyCode) ? true : false;
        }
    }
}
